# fly.toml app configuration file generated for ay4kal-discord-music-bot on 2024-05-15T01:03:13+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ay4kal-discord-music-bot'
primary_region = 'nrt'

[build]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
